// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnionArchitecture.RepositoryLayer;

namespace OnionArchitecture.RepositoryLayer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210622211031_PopularCustomer")]
    partial class PopularCustomer
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OnionArchitecture.DomainLayer.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_date");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(200)")
                        .HasColumnName("Customer_Name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("modified_date");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)")
                        .HasColumnName("payment_type");

                    b.Property<string>("PurchasesProduct")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("purchased_product");

                    b.HasKey("Id")
                        .HasName("pk_customerid");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2021, 6, 22, 18, 10, 30, 697, DateTimeKind.Local).AddTicks(7016),
                            CustomerName = "João Augusto",
                            IsActive = false,
                            ModifiedDate = new DateTime(2021, 6, 22, 18, 10, 30, 702, DateTimeKind.Local).AddTicks(2510),
                            PaymentType = "Cartão",
                            PurchasesProduct = "S"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2021, 6, 22, 18, 10, 30, 702, DateTimeKind.Local).AddTicks(3215),
                            CustomerName = "Maria Augusta",
                            IsActive = true,
                            ModifiedDate = new DateTime(2021, 6, 22, 18, 10, 30, 702, DateTimeKind.Local).AddTicks(3220),
                            PaymentType = "Dinheiro",
                            PurchasesProduct = "S"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2021, 6, 22, 18, 10, 30, 702, DateTimeKind.Local).AddTicks(3223),
                            CustomerName = "José Augusto Rodrigues",
                            IsActive = true,
                            ModifiedDate = new DateTime(2021, 6, 22, 18, 10, 30, 702, DateTimeKind.Local).AddTicks(3224),
                            PaymentType = "Cheque",
                            PurchasesProduct = "S"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2021, 6, 22, 18, 10, 30, 702, DateTimeKind.Local).AddTicks(3226),
                            CustomerName = "Fernando Medeiros de Almeida",
                            IsActive = false,
                            ModifiedDate = new DateTime(2021, 6, 22, 18, 10, 30, 702, DateTimeKind.Local).AddTicks(3227),
                            PaymentType = "Cartão Débito",
                            PurchasesProduct = "S"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2021, 6, 22, 18, 10, 30, 702, DateTimeKind.Local).AddTicks(3230),
                            CustomerName = "João Alfredo",
                            IsActive = true,
                            ModifiedDate = new DateTime(2021, 6, 22, 18, 10, 30, 702, DateTimeKind.Local).AddTicks(3231),
                            PaymentType = "Pix",
                            PurchasesProduct = "S"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
